### ISSUE TITLE
can't download the data

### ISSUE THREAD

**Issue by mingzhaochina** [jamesaud/seismic-analysis-toolbox#1]
First really admire your 4 million waveforms!

However,afer I build the docker successfully,when using ultimate_downloader.py to download the waveform,there will be error message:

Traceback (most recent call last):
  File "main_download.py", line 100, in <module>
    validate_and_adjust_starttime(attempts)
  File "main_download.py", line 97, in validate_and_adjust_starttime
    raise Exception("Couldn't download from server.")
Exception: Couldn't download from server.

and 

Traceback (most recent call last):
  File "main_download.py", line 108, in <module>
    network.select(STATION).plot(projection='local')
  File "/opt/conda/lib/python3.6/site-packages/obspy/core/inventory/network.py", line 531, in plot
    from obspy.imaging.maps import plot_map
  File "/opt/conda/lib/python3.6/site-packages/obspy/imaging/maps.py", line 33, in <module>
    from mpl_toolkits.basemap import Basemap
  File "/opt/conda/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py", line 16, in <module>
    from matplotlib.cbook import is_scalar, dedent
ImportError: cannot import name 'is_scalar'

No data was downloaded successfully

**Comment by jamesaud** [comment]
I'm gone this weekend but I'll check on this early next week and let you know!

**Comment by mingzhaochina** [comment]
Wow,a prompt reply!Thanks^_^
![image](https://user-images.githubusercontent.com/25214086/54697412-7bf75700-4b68-11e9-9257-668cf8461b35.png)

using docker ps -a I can see a lot of docker container were created but none of them download data.

While waiting for your reply,I will try to find the problem myself.This is a very interesting code,thanks for share!

**Comment by mingzhaochina** [comment]
I think this is a problem of client.get_waveforms

**Comment by jamesaud** [comment]
You can try again on the branch "2019" and see how it works for you?

**Comment by mingzhaochina** [comment]
Thanks,it happens I am working on this now^_^I will try it tomorrow.

Now I almost finish build my own dataset using the writer pipeline your
provided.I will have a try of the training part tomorrow.I have tried to do
the training with waveform directly but never try the spectrogram. I am
looking forward to see the results!

**Comment by mingzhaochina** [comment]
Now it is just too late here,I will continue tomorrow

Zhao Ming <mingzhao.china@gmail.com> 于2019年3月28日周四 下午11:55写道：

> Thanks,it happens I am working on this now^_^I will try it tomorrow.
>
> Now I almost finish build my own dataset using the writer pipeline your
> provided.I will have a try of the training part tomorrow.I have tried to do
> the training with waveform directly but never try the spectrogram. I am
> looking forward to see the results!
>

**Comment by mingzhaochina** [comment]
I tried your newest code,it works perfectly on my computer.Thanks！

Zhao Ming <mingzhao.china@gmail.com> 于2019年3月28日周四 下午11:56写道：

> Now it is just too late here,I will continue tomorrow
>
> Zhao Ming <mingzhao.china@gmail.com> 于2019年3月28日周四 下午11:55写道：
>
>> Thanks,it happens I am working on this now^_^I will try it tomorrow.
>>
>> Now I almost finish build my own dataset using the writer pipeline your
>> provided.I will have a try of the training part tomorrow.I have tried to do
>> the training with waveform directly but never try the spectrogram. I am
>> looking forward to see the results!
>>
>

**Comment by mingzhaochina** [comment]
so far I downloaded 631883 waveforms of  370 stations and 510515 spectrograms of 124 stations.However,in the inventory there are 4072 stations,most of them failed to be downloaded.

**Comment by jamesaud** [comment]
It's calling the file 'https://github.com/jamesaud/seismic-analysis-toolbox/blob/2019/seismic_toolbox/main_download.py', check the global variables of that file. You can modify the max radius, minimum number of events and noise, etc.  

The "strict" requirements that I have set limits the downloads  to fit this criteria

**Comment by jamesaud** [comment]
# These variables:
    NUM_EVENTS = 1000
    NUM_NOISE_EVENTS = 1000
    MAX_RADIUS = 4
    DURATION = args.duration
    MIN_EVENTS = 300
    MIN_MAGNITUDE = None
    NOISE_TIMESPAN = Day(60)
    ATTEMPTS = 30

**Comment by mingzhaochina** [comment]
Hi Jame,

Now I can use your code and my own data to train model😁But it seems the
gpu can't be used on my computer,I have three cards,like this

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.48
  |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr.
ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute
M. |
|===============================+======================+======================|
|   0  TITAN Xp            Off  | 00000000:02:00.0  On |
N/A |
| 41%   67C    P2    86W / 250W |   2094MiB / 12194MiB |      0%
Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:03:00.0 Off |
N/A |
| 31%   45C    P8    16W / 250W |     12MiB / 11178MiB |      0%
Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:81:00.0 Off |
N/A |
| 29%   33C    P8    15W / 250W |     12MiB / 11178MiB |      0%
Default |
+-------------------------------+----------------------+----------------------+

And my environment should contain the cuda version needed. I think your
code is a cuda version,because I can see these in the main.py:

main.py:net = NET().cuda()
main.py:criterion = nn.CrossEntropyLoss().cuda()
main.py:        images = [Variable(image).cuda() for image in images]
main.py:        Net = NET().cuda()
main.py:        inputs, labels = [Variable(input).cuda() for input in
inputs], labels
main.py:        inputs, labels = [Variable(input).cuda() for input in
true_inputs], Variable(true_labels).cuda()

so I wonder if you can use your code under GPU environment smoothly

jamesaud <notifications@github.com> 于2019年3月31日周日 下午6:03写道：

**Comment by mingzhaochina** [comment]
I am sorry to bother but I think the gpu is actually running,although the
speed doesn't become faster obviously
[image: image.png]


Zhao Ming <mingzhao.china@gmail.com> 于2019年4月20日周六 下午5:55写道：

**Comment by jamesaud** [comment]
Hi, I moved the issue: https://github.com/jamesaud/earthquake-detector-9000/issues/1#issue-435949606
